package com.xielei.common;

import com.jfinal.plugin.activerecord.Page;
import com.xielei.common.model.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	public static final Article dao = new Article().dao();
	
	public Page<Article> paginate(int pageNumber, int pageSize) {
		return dao.paginate(pageNumber, pageSize, "SELECT *", "FROM article ORDER BY addtime DESC");
	}
	
	public Article findById(int id) {
		return dao.findById(id);
	}
	
	public void deleteById(int id) {
		dao.deleteById(id);
	}
}
