package com.xielei.common.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setLike(java.lang.Integer like) {
		set("like", like);
		return (M)this;
	}

	public java.lang.Integer getLike() {
		return get("like");
	}

	public M setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
		return (M)this;
	}

	public java.util.Date getAddtime() {
		return get("addtime");
	}

}
