package com.xielei.common.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setGroup(java.lang.String group) {
		set("group", group);
		return (M)this;
	}

	public java.lang.String getGroup() {
		return get("group");
	}

	public M setKey(java.lang.String key) {
		set("key", key);
		return (M)this;
	}

	public java.lang.String getKey() {
		return get("key");
	}

	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}

	public java.lang.String getValue() {
		return get("value");
	}

}
